import React from 'react';
import { theme as defaultTheme } from '../../constants';
export declare const ThemeContext: React.Context<{
    layoutColor: string;
    fontFamily: string;
    backgroundInput: string;
    inputColor: string;
    borderInputColor: string;
    inputFontSize: number;
    labelSize: number;
    labelColor: string;
    loadingColor: string;
    loadingTextColor: string;
    loadingDescriptionColor: string;
    loadingSecondaryDescriptionColor: string;
    primaryColor: string;
    badgeInitialsColor: string;
    badgeInitialsBg: string;
    badgeInitialsSize: number;
    titleColor: string;
    titleSize: number;
    descriptionColor: string;
    descriptionSize: number;
    calendarTextDisabled: string;
    calendarToday: string;
    calendarSelected: string;
    calendarDisabledDay: string;
    calendarActivesDays: string;
    calendarMonth: string;
    calendarDaysOfWeek: string;
    buttonActive: string;
    buttonDisabled: string;
    buttonTextActive: string;
    buttonTextDisabled: string;
    backgroundColorCancel: string;
    textColorCancel: string;
    backgroundSelect: string;
    colorRadiusSelect: string;
    primaryColorSelect: string;
    secondaryColorSelect: string;
    colorAmount: string;
    colorAmountPlaceholder: string;
    sizeAmount: number;
    opacityAmount: number;
    reviewLabelColor: string;
    reviewLabelSize: number;
    reviewValueColor: string;
    reviewValueSize: number;
}>;
export interface IThemeProvider {
    theme: typeof defaultTheme;
}
export declare const ThemeProvider: React.FC<IThemeProvider>;
